version: '3.8'

services:
  angeli-backend:
    build: .
    container_name: angeli-backend
    ports:
      - "8005:8005"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
    command: uvicorn main:app --host 0.0.0.0 --port 8005 --reload